package io.github.dawidprosba.aergiadevkit.ksp.hytale_codec.processor.strategy

import io.github.dawidprosba.aergiadevkit.ksp.hytale_codec.annotations.CodecProperty
import io.github.dawidprosba.aergiadevkit.ksp.hytale_codec.annotations.validators.CodecProjectileValidator
import io.github.dawidprosba.aergiadevkit.ksp.hytale_codec.annotations.validators.CodecRequiredValidator
import io.github.dawidprosba.aergiadevkit.ksp.hytale_codec.validators.CODEC_PROJECTILE_VALIDATOR_TEMPLATE
import io.github.dawidprosba.aergiadevkit.ksp.hytale_codec.validators.CODEC_REQUIRED_VALIDATOR_TEMPLATE
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSAnnotation
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import kotlin.reflect.KClass

// --- Hytale Codec Types ---
private val CODEC_TYPE = ClassName("com.hypixel.hytale.codec", "Codec")
private val KEYED_CODEC_TYPE = ClassName("com.hypixel.hytale.codec", "KeyedCodec")
private val BUILDER_CODEC_TYPE = ClassName("com.hypixel.hytale.codec.builder", "BuilderCodec")

class CodecFileGeneratorStrategy(
    private val classDeclaration: KSClassDeclaration,
    private val properties: List<KSPropertyDeclaration>,
    private val codeGenerator: CodeGenerator
) {
    private val packageName = classDeclaration.packageName.asString()
    private val className = classDeclaration.simpleName.asString()
    private val classTypeName = ClassName(packageName, className)
    private val supportedValidators: Map<KClass<*>, String> = mapOf(
        CodecRequiredValidator::class to CODEC_REQUIRED_VALIDATOR_TEMPLATE,
        CodecProjectileValidator::class to CODEC_PROJECTILE_VALIDATOR_TEMPLATE
    )

    fun generate() {
        val fileSpec = FileSpec.builder(packageName, "${className}Codec")
            .addFileComment("Auto-generated by HytaleCodecProcessor. Do not edit manually.")
            .addProperty(buildCodecProperty())
            .build()

        codeGenerator.createNewFile(
            dependencies = Dependencies(false, classDeclaration.containingFile!!),
            packageName = packageName,
            fileName = "${className}Codec"
        ).use { stream ->
            stream.writer().use { fileSpec.writeTo(it) }
        }
    }

    // --- Property ---

    private fun buildCodecProperty(): PropertySpec {
        return PropertySpec
            .builder(
                "CodecBuilder${className}",
                // BuilderCodec<ProjectileConfig>
                BUILDER_CODEC_TYPE.parameterizedBy(classTypeName)
            )
            .initializer(buildCodecInitializer())
            .build()
    }

    private fun buildCodecInitializer(): CodeBlock {
        val parentCodec = resolveParentCodec()

        return CodeBlock.builder()
            .apply {
                if (parentCodec != null) {
                    // BuilderCodec.builder(ProjectileConfig::class.java, ::ProjectileConfig, ParentClass.codec)
                    add(
                        "%T.builder(%T::class.java, ::%T, %L)\n",
                        BUILDER_CODEC_TYPE,
                        classTypeName,
                        classTypeName,
                        parentCodec
                    )
                } else {
                    // BuilderCodec.builder(ProjectileConfig::class.java, ::ProjectileConfig)
                    add(
                        "%T.builder(%T::class.java, ::%T)\n",
                        BUILDER_CODEC_TYPE,
                        classTypeName,
                        classTypeName
                    )
                }
            }
            .apply {
                properties.forEach { property ->
                    addPropertyCodecChain(this, property)
                }
            }
            .add(".build()")
            .build()
    }

    private fun resolveParentCodec(): CodeBlock? {
        val superType = classDeclaration.superTypes
            .map { it.resolve() }
            .firstOrNull { superType ->
                val superClass =
                    superType.declaration as? KSClassDeclaration ?: return@firstOrNull false
                val companion = superClass.declarations
                    .filterIsInstance<KSClassDeclaration>()
                    .firstOrNull { it.isCompanionObject }

                companion?.getAllProperties()?.any {
                    it.simpleName.asString() == "CODEC"  // ← uppercase
                } ?: false
            } ?: return null

        val superClass = superType.declaration as KSClassDeclaration
        val superPackage = superClass.packageName.asString()
        val superName = superClass.simpleName.asString()

        return CodeBlock.of("%T.CODEC", ClassName(superPackage, superName))  // ← uppercase
    }

    // --- Property Chain ---

    private fun isInheritedProperty(property: KSPropertyDeclaration): Boolean {
        return property.parentDeclaration != classDeclaration
    }

    private fun isCodecType(property: KSPropertyDeclaration): Boolean {
        val typeDeclaration =
            property.type.resolve().declaration as? KSClassDeclaration ?: return false
        val companion = typeDeclaration.declarations
            .filterIsInstance<KSClassDeclaration>()
            .firstOrNull { it.isCompanionObject } ?: return false
        return companion.getAllProperties().any { it.simpleName.asString() == "CODEC" }
    }

    private fun addPropertyCodecChain(
        builder: CodeBlock.Builder,
        property: KSPropertyDeclaration
    ) {
        val propertyName = property.simpleName.asString()
        val args = property.getAnnotationArgs(CodecProperty::class.simpleName!!)
        val documentation = args["documentation"] as? String ?: ""
        val required = args["required"] as? Boolean ?: true
        val isInherited = isInheritedProperty(property) || isCodecType(property)

        // Capitalize property name for KeyedCodec key e.g. "homingConfig" -> "HomingConfig"
        val codecKey = propertyName.replaceFirstChar { it.uppercaseChar() }

        // Resolve either Codec.STRING / Codec.INT etc. or HomingProjectileConfig.codec
        val resolvedCodec = resolveCodec(property)

        if (isInherited) {
            builder
                // .appendInherited(KeyedCodec("ProjectileId", Codec.STRING, true),
                .add(
                    ".appendInherited(%T(%S, %L, %L),\n",
                    KEYED_CODEC_TYPE,
                    codecKey,
                    resolvedCodec,
                    required
                )
                //     { config, value -> config.projectileId = value },
                .add("    { config, value -> config.%N = value },\n", propertyName)
                //     { config -> config.projectileId },
                .add("    { config -> config.%N },\n", propertyName)
                //     { target, parent -> target.projectileId = parent.projectileId }
                .add(
                    "    { target, parent -> target.%N = parent.%N }\n",
                    propertyName,
                    propertyName
                )
                .add(")\n")
        } else {
            builder
                // .append(KeyedCodec("HomingConfig", HomingProjectileConfig.codec, true),
                .add(
                    ".append(%T(%S, %L, %L),\n",
                    KEYED_CODEC_TYPE,
                    codecKey,
                    resolvedCodec,
                    required
                )
                //     { config, value -> config.homingConfig = value },
                .add("    { config, value -> config.%N = value },\n", propertyName)
                //     { config -> config.homingConfig }
                .add("    { config -> config.%N }\n", propertyName)
                .add(")\n")
        }

        // .documentation("Homing behavior config for this projectile.")
        if (documentation.isNotEmpty()) {
            builder.add(".documentation(%S)\n", documentation)
        }


//        var validatorAnnotations = supportedValidators.mapNotNull { validator ->
//            property.getAnnotation(validator.simpleName!!)
//        }

        supportedValidators.forEach { (validatorClass, template) ->
            val annotation = property.annotations.find { annotation ->
                annotation.shortName.asString() == validatorClass.simpleName
            }
            if(annotation == null) {
                return@forEach
            }
            // .addValidator(template)
            builder.add(".addValidator(%L)\n", template)
        }


        // .add()
        builder.add(".add()\n")
    }

    // --- Codec Type Resolver ---

    private fun resolveCodec(property: KSPropertyDeclaration): CodeBlock {
        val type = property.type.resolve()
        val qualifiedName = type.declaration.qualifiedName?.asString()

        return when (qualifiedName) {
            // Primitive types → built-in Codec constants
            "kotlin.String" -> CodeBlock.of("%T.STRING", CODEC_TYPE)
            "kotlin.Int" -> CodeBlock.of("%T.INT", CODEC_TYPE)
            "kotlin.Boolean" -> CodeBlock.of("%T.BOOLEAN", CODEC_TYPE)
            "kotlin.Float" -> CodeBlock.of("%T.FLOAT", CODEC_TYPE)
            "kotlin.Double" -> CodeBlock.of("%T.DOUBLE", CODEC_TYPE)
            "kotlin.Long" -> CodeBlock.of("%T.LONG", CODEC_TYPE)
            else -> {
                // Complex type → use its own CODEC field e.g. HomingProjectileConfig.CODEC
                val typePackage = type.declaration.packageName.asString()
                val typeName = type.declaration.simpleName.asString()
                CodeBlock.of("%T.CODEC", ClassName(typePackage, typeName))
            }
        }
    }
}

// --- Top-level KSP Extensions ---

private fun KSAnnotated.getAnnotation(simpleName: String): KSAnnotation? {
    return annotations.firstOrNull { it.shortName.asString() == simpleName }
}

private fun KSAnnotated.getAnnotationArgs(simpleName: String): Map<String?, Any?> {
    return getAnnotation(simpleName)
        ?.arguments
        ?.associate { it.name?.asString() to it.value }
        ?: emptyMap()
}