package io.github.dawidprosba.aergiadevkit.ksp.hytalecodec.processor.generators

import io.github.dawidprosba.aergiadevkit.ksp.hytalecodec.annotations.CodecProperty
import io.github.dawidprosba.aergiadevkit.ksp.hytalecodec.annotations.validators.CodecProjectileValidator
import io.github.dawidprosba.aergiadevkit.ksp.hytalecodec.annotations.validators.CodecRequiredValidator
import io.github.dawidprosba.aergiadevkit.ksp.hytalecodec.validators.CODEC_PROJECTILE_VALIDATOR_TEMPLATE
import io.github.dawidprosba.aergiadevkit.ksp.hytalecodec.validators.CODEC_REQUIRED_VALIDATOR_TEMPLATE
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import io.github.dawidprosba.aergiadevkit.ksp.extensions.getAnnotation
import io.github.dawidprosba.aergiadevkit.ksp.extensions.getArgs
import io.github.dawidprosba.aergiadevkit.ksp.extensions.getCompanionPropertiesFromParentClass
import io.github.dawidprosba.aergiadevkit.ksp.extensions.hasAnyCompanionProperty
import io.github.dawidprosba.aergiadevkit.ksp.extensions.isInheritedProperty
import io.github.dawidprosba.aergiadevkit.ksp.hytalecodec.data.CodecPropertyData
import kotlin.reflect.KClass

// --- Hytale Codec Types ---
private val HYTALE_CODEC_TYPE = ClassName("com.hypixel.hytale.codec", "Codec")
private val HYTALE_KEYED_CODEC_TYPE = ClassName("com.hypixel.hytale.codec", "KeyedCodec")
private val HYTALE_BUILDER_CODEC_TYPE =
    ClassName("com.hypixel.hytale.codec.builder", "BuilderCodec")
private val PRIMITIVE_HYTALE_CODECS = mapOf(
    "kotlin.String" to "STRING",
    "kotlin.Int" to "INT",
    "kotlin.Boolean" to "BOOLEAN",
    "kotlin.Float" to "FLOAT",
    "kotlin.Double" to "DOUBLE",
    "kotlin.Long" to "LONG",
)


class CodecFileGenerator(
    private val classDeclaration: KSClassDeclaration,
    private val properties: List<KSPropertyDeclaration>,
    private val codeGenerator: CodeGenerator
) {
    private val generatedFilePackage = classDeclaration.packageName.asString()
    private val className = classDeclaration.simpleName.asString()
    private val classTypeName = ClassName(generatedFilePackage, className)
    private val generatedFileName = "${className}Codec"
    private val generatedPropertyName = "CodecBuilder${className}"
    private val generatedPropertyType = HYTALE_BUILDER_CODEC_TYPE.parameterizedBy(classTypeName)
    private val expectedCodecProperty =
        "CODEC" // This is the name of property that codec will look for in companion object
    private val supportedValidators: Map<KClass<*>, String> = mapOf(
        CodecRequiredValidator::class to CODEC_REQUIRED_VALIDATOR_TEMPLATE,
        CodecProjectileValidator::class to CODEC_PROJECTILE_VALIDATOR_TEMPLATE
    )
    private val codecPropertyAnnotationName = CodecProperty::class.simpleName!!

    fun generate() {
        val fileSpec = FileSpec.builder(generatedFilePackage, generatedFileName)
            .addFileComment("Auto-generated by hytale-aergia-mod-devkit. Changes here will be overwritten, do not edit manually.")
            .addProperty(createCodecBuilderProperty())
            .build()

        codeGenerator.createNewFile(
            dependencies = Dependencies(false, classDeclaration.containingFile!!),
            packageName = generatedFilePackage,
            fileName = "${className}Codec"
        ).use { stream ->
            stream.writer().use { fileSpec.writeTo(it) }
        }
    }

    /**
     * Creates property declaration for the generated codec builder.
     */
    private fun createCodecBuilderProperty(): PropertySpec {
        return PropertySpec
            .builder(
                generatedPropertyName,
                generatedPropertyType
            )
            .initializer(buildCodecInitializer())
            .build()
    }


    private fun buildCodecInitializer(): CodeBlock {
        val parentCodecProperties =
            classDeclaration.getCompanionPropertiesFromParentClass(expectedCodecProperty)
        val codecFromParent = parentCodecProperties[expectedCodecProperty]

        val codeBlockBuilder = CodeBlock.builder()

        // Codec was not found, then we don't want to add it as parameter for inheritance.
        if (codecFromParent == null) {
            codeBlockBuilder.add(
                "%T.builder(%T::class.java, ::%T)\n",
                HYTALE_BUILDER_CODEC_TYPE,
                classTypeName,
                classTypeName
            )
        } else {
            codeBlockBuilder.add(
                "%T.builder(%T::class.java, ::%T, %L)\n",
                HYTALE_BUILDER_CODEC_TYPE,
                classTypeName,
                classTypeName,
                codecFromParent
            )
        }

        properties.forEach { property ->
            addPropertyCodecChain(codeBlockBuilder, property)
        }

        return codeBlockBuilder.build()
    }


    /**
     * Checks if the property is nested.
     * This checks if the property is a class, and that class has a "CODEC" property.
     * If it does, this means it's nested and we need to treat it as inherited in codec builder.
     * This is to avoid bug when values wouldn't be read correctly from .json (or HytaleEditor).
     */
    private fun hasCodecProperty(property: KSPropertyDeclaration): Boolean {
        return (property.type.resolve().declaration as? KSClassDeclaration)
            ?.hasAnyCompanionProperty(expectedCodecProperty)
            ?: false
    }

    private fun getCodecPropertyData(property: KSPropertyDeclaration): CodecPropertyData {
        val annotation = property.getAnnotation(codecPropertyAnnotationName)
        val args = annotation?.getArgs()
            ?: throw IllegalArgumentException("@$codecPropertyAnnotationName is missing arguments on ${property.simpleName.asString()}")

        val treatAsInherited =
            property.isInheritedProperty(classDeclaration) || hasCodecProperty(property)

        try {
            return CodecPropertyData(
                annotationArgs = args,
                isInherited = treatAsInherited
            )
        } catch (e: Exception) {
            throw IllegalArgumentException(
                "Failed to parse @$codecPropertyAnnotationName on ${property.simpleName.asString()}",
                e
            )
        }
    }

    private fun addInheritedPropertyCodecChain(
        builder: CodeBlock.Builder,
        property: KSPropertyDeclaration,
        data: CodecPropertyData,
    ) {
        val propertyName = property.simpleName.asString()
        val codecKey = propertyName.replaceFirstChar { it.uppercase() }
        val resolvedCodec = resolveCodecSchemaType(property)

        builder.add(
            ".appendInherited(%T(%S, %L, %L),\n",
            HYTALE_KEYED_CODEC_TYPE,
            codecKey,
            resolvedCodec,
            data.required,
        )
            .add("    { config, value -> config.%N = value },\n", propertyName)
            .add("    { config -> config.%N },\n", propertyName)
            .add(
                "    { target, parent -> target.%N = parent.%N }\n",
                propertyName,
                propertyName
            )
            .add(")\n")
    }

    private fun addNormalPropertyCodecChain(
        builder: CodeBlock.Builder,
        property: KSPropertyDeclaration,
        data: CodecPropertyData,
    ) {
        val propertyName = property.simpleName.asString()
        val codecKey = propertyName.replaceFirstChar { it.uppercase() }
        val resolvedCodec = resolveCodecSchemaType(property)

        builder
            .add(
                ".append(%T(%S, %L, %L),\n",
                HYTALE_KEYED_CODEC_TYPE,
                codecKey,
                resolvedCodec,
                data.treatAsInherited
            )
            .add("    { config, value -> config.%N = value },\n", propertyName)
            .add("    { config -> config.%N }\n", propertyName)
            .add(")\n")
    }

    private fun addValidators(builder: CodeBlock.Builder, property: KSPropertyDeclaration) {
        supportedValidators.forEach { (validatorClass, template) ->
            val annotation = property.annotations.find { annotation ->
                annotation.shortName.asString() == validatorClass.simpleName
            }
            if (annotation == null) {
                return@forEach
            }
            // .addValidator(template)
            builder.add(".addValidator(%L)\n", template)
        }
    }

    private fun addPropertyCodecChain(
        builder: CodeBlock.Builder,
        property: KSPropertyDeclaration
    ) {
        val data = getCodecPropertyData(property)

        if (data.treatAsInherited) {
            addInheritedPropertyCodecChain(builder, property, data)
        } else {
            addNormalPropertyCodecChain(builder, property, data)
        }

        // Add Documentation
        builder.add(".documentation(%S)\n", data.documentation)
        addValidators(builder, property)
        // End
        builder.add(".add()\n")
    }

    private fun resolveCodecSchemaType(property: KSPropertyDeclaration): CodeBlock {
        val type = property.type.resolve()
        val qualifiedName = type.declaration.qualifiedName?.asString()

        // Handle If Type can be mapped to Hytale Primitive Codec Type
        PRIMITIVE_HYTALE_CODECS[qualifiedName]?.let { constant ->
            return CodeBlock.of("%T.$constant", HYTALE_CODEC_TYPE)
        }

        val typePackage = type.declaration.packageName.asString()
        val typeName = type.declaration.simpleName.asString()

        // If it's not a primitive type, we assume it's a complex type with its own CODEC field e.g. HomingProjectileConfig.CODEC
        return CodeBlock.of("%T.CODEC", ClassName(typePackage, typeName))
    }
}