package io.github.dawidprosba.aergiadevkit.ksp.hytalecodec.processor.generators

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFile
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import io.github.dawidprosba.aergiadevkit.ksp.hytalecodec.providers.CodecRegistrationService

private val BUILDER_CODEC_TYPE = ClassName("com.hypixel.hytale.codec.builder", "BuilderCodec")
private val CODEC_REGISTRATION_SERVICE_TYPE = ClassName(
    "io.github.dawidprosba.aergiadevkit.ksp.hytalecodec.providers",
    "CodecRegistrationService"
)

class CodecRegistryGenerator(
    private val outputPackage: String,
    private val classDeclarations: List<KSClassDeclaration>,
    private val sourceFiles: Array<KSFile>,
    private val codeGenerator: CodeGenerator,
) {
    private val objectName = "CodecRegistryGenerated"

    fun generate() {
        generateSourceFile()
        generateServiceLoaderFile()
    }

    private fun generateSourceFile() {
        val fileSpec = FileSpec.builder(outputPackage, objectName)
            .addFileComment("Auto-generated by RegistrationProcessor. Do not edit manually.")
            .addType(buildRegistryClass())
            .build()

        codeGenerator.createNewFile(
            dependencies = Dependencies(true, *sourceFiles),
            packageName = outputPackage,
            fileName = objectName,
        ).use { stream ->
            stream.writer().use { fileSpec.writeTo(it) }
        }
    }

    private fun generateServiceLoaderFile() {
        val serviceInterfaceName = CodecRegistrationService::class.qualifiedName!!
        val serviceClassName = "$outputPackage.$objectName"

        codeGenerator.createNewFile(
            dependencies = Dependencies(true, *sourceFiles),
            packageName = "META-INF.services",
            fileName = serviceInterfaceName,
            extensionName = "",
        ).use { stream ->
            stream.write(serviceClassName.toByteArray())
        }
    }

    private fun buildRegistryClass(): TypeSpec {
        return TypeSpec.classBuilder(objectName)
            .addSuperinterface(CODEC_REGISTRATION_SERVICE_TYPE)
            .addFunction(buildRegisterAllFunction())
            .build()
    }

    private fun buildRegisterAllFunction(): FunSpec {
        val classStarType = ClassName("java.lang", "Class").parameterizedBy(STAR)
        val codecStarType = BUILDER_CODEC_TYPE.parameterizedBy(STAR)
        val returnType = ClassName("kotlin.collections", "MutableMap").parameterizedBy(classStarType, codecStarType)

        return FunSpec.builder("registerAll")
            .addModifiers(KModifier.OVERRIDE)
            .returns(returnType)
            .addCode(buildRegisterAllBody(classStarType, codecStarType))
            .build()
    }

    private fun buildRegisterAllBody(classStarType: TypeName, codecStarType: TypeName): CodeBlock {
        return CodeBlock.builder().apply {
            addStatement("val result = mutableMapOf<%T, %T>()", classStarType, codecStarType)
            classDeclarations.forEach { declaration ->
                val packageName = declaration.packageName.asString()
                val className = declaration.simpleName.asString()
                val classType = ClassName(packageName, className)
                val codecPropertyName = MemberName(packageName, "CodecBuilder$className")
                addStatement("result[%T::class.java] = %M", classType, codecPropertyName)
            }
            addStatement("return result")
        }.build()
    }
}
