package io.github.dawidprosba.aergiadevkit.ksp.pipeline.generating_steps

import com.squareup.kotlinpoet.FileSpec
import io.github.dawidprosba.aergiadevkit.ksp.pipeline.PipelineStep
import io.github.dawidprosba.aergiadevkit.ksp.pipeline.generating_steps.data.FileSpecOptions

class BuildFileSpecStep : PipelineStep<FileSpecOptions, FileSpec> {
    override fun process(input: FileSpecOptions): FileSpec {
        return FileSpec.builder(input.outputPackage, input.outputClassName)
            .addFileComment("Auto-generated by RegistrationProcessor. Do not edit manually.")
            .addType(input.content)
            .build()
    }
}