package io.github.dawidprosba.aergiadevkit.ksp.registry.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSFile
import com.squareup.kotlinpoet.*

class GlobalEventRegistryGenerator(
    private val outputPackage: String,
    private val pluginClass: String,
    private val entries: List<GlobalEventEntryMetadata>,
    private val sourceFiles: Array<KSFile>,
    private val codeGenerator: CodeGenerator
) {
    fun generate() {
        val fileSpec = FileSpec.builder(outputPackage, OBJECT_NAME)
            .addFileComment("Auto-generated by RegistrationProcessor. Do not edit manually.")
            .addType(buildRegistryObject())
            .build()

        codeGenerator.createNewFile(
            dependencies = Dependencies(true, *sourceFiles),
            packageName = outputPackage,
            fileName = OBJECT_NAME
        ).use { stream ->
            stream.writer().use { fileSpec.writeTo(it) }
        }
    }

    private fun buildRegistryObject(): TypeSpec {
        return TypeSpec.objectBuilder(OBJECT_NAME)
            .addProperty(buildLoggerProperty())
            .addFunction(buildRegisterAllFunction())
            .build()
    }

    private fun buildLoggerProperty(): PropertySpec {
        val pluginClassName = ClassName.bestGuess(pluginClass)
        return PropertySpec.builder("LOGGER", HYTALE_LOGGER_TYPE)
            .initializer("%T.get(%T::class.simpleName)", HYTALE_LOGGER_TYPE, pluginClassName)
            .build()
    }

    private fun buildRegisterAllFunction(): FunSpec {
        return FunSpec.builder("registerAll")
            .addParameter("registry", EVENT_REGISTRY_TYPE)
            .addCode(buildRegisterAllBody())
            .build()
    }

    private fun buildRegisterAllBody(): CodeBlock {
        return CodeBlock.builder().apply {
            entries.forEach { entry ->
                val eventClass = ClassName.bestGuess(entry.eventClassQualifiedName)
                val containingClass = ClassName.bestGuess(entry.containingClassQualifiedName)
                if (!entry.enabled) {
                    addStatement(
                        "LOGGER.atWarning().log(%S, %S)",
                        "Skipping global event '%s' (%s), reason -> disabled",
                        entry.functionQualifiedName
                    )
                } else if (entry.hasEventParam) {
                    addStatement(
                        "%M(%T::class, { event -> %T.Companion.%N(event) }, registry, %S)",
                        REGISTER_GLOBAL_EVENT, eventClass, containingClass, entry.functionName, entry.functionName
                    )
                } else {
                    addStatement(
                        "%M(%T::class, { %T.Companion.%N() }, registry, %S)",
                        REGISTER_GLOBAL_EVENT, eventClass, containingClass, entry.functionName, entry.functionName
                    )
                }
            }
        }.build()
    }

    private companion object {
        const val OBJECT_NAME = "GlobalEventRegistryGenerated"
    }
}
