package io.github.dawidprosba.aergiadevkit.ksp.registry.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSFile
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy

class InteractionRegistryGenerator(
    private val outputPackage: String,
    private val pluginClass: String,
    private val entries: List<RegistryEntryMetadata>,
    private val sourceFiles: Array<KSFile>,
    private val codeGenerator: CodeGenerator
) {
    fun generate() {
        val fileSpec = FileSpec.builder(outputPackage, OBJECT_NAME)
            .addFileComment("Auto-generated by RegistrationProcessor. Do not edit manually.")
            .addType(buildRegistryObject())
            .build()

        codeGenerator.createNewFile(
            dependencies = Dependencies(true, *sourceFiles),
            packageName = outputPackage,
            fileName = OBJECT_NAME
        ).use { stream ->
            stream.writer().use { fileSpec.writeTo(it) }
        }
    }

    private fun buildRegistryObject(): TypeSpec {
        return TypeSpec.objectBuilder(OBJECT_NAME)
            .addProperty(buildLoggerProperty())
            .addFunction(buildRegisterAllFunction())
            .build()
    }

    private fun buildLoggerProperty(): PropertySpec {
        val pluginClassName = ClassName.bestGuess(pluginClass)
        return PropertySpec.builder("LOGGER", HYTALE_LOGGER_TYPE)
            .initializer("%T.get(%T::class.simpleName)", HYTALE_LOGGER_TYPE, pluginClassName)
            .build()
    }

    private fun buildRegisterAllFunction(): FunSpec {
        val registryParamType = CODEC_MAP_REGISTRY_ASSETS_TYPE.parameterizedBy(INTERACTION_TYPE, STAR)
        return FunSpec.builder("registerAll")
            .addParameter("registry", registryParamType)
            .addCode(buildRegisterAllBody())
            .build()
    }

    private fun buildRegisterAllBody(): CodeBlock {
        return CodeBlock.builder().apply {
            entries.forEach { entry ->
                val entryClass = ClassName.bestGuess(entry.qualifiedName)
                if (!entry.enabled) {
                    addStatement(
                        "LOGGER.atWarning().log(%S, %S)",
                        "Skipping interaction '%s' (%s), reason -> disabled",
                        entry.qualifiedName
                    )
                } else {
                    addStatement("%M(%T::class, registry)", REGISTER_INTERACTION, entryClass)
                }
            }
        }.build()
    }

    private companion object {
        const val OBJECT_NAME = "InteractionRegistryGenerated"
    }
}
