package io.github.dawidprosba.aergiadevkit.ksp.registry.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSFile
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy

// --- Hytale Registry Types ---
private val HYTALE_LOGGER_TYPE = ClassName("com.hypixel.hytale.logger", "HytaleLogger")
private val CODEC_MAP_REGISTRY_ASSETS_TYPE =
    ClassName("com.hypixel.hytale.server.core.plugin.registry", "CodecMapRegistry", "Assets")
private val INTERACTION_TYPE = ClassName(
    "com.hypixel.hytale.server.core.modules.interaction.interaction.config",
    "Interaction"
)
private val COMPONENT_REGISTRY_PROXY_TYPE =
    ClassName("com.hypixel.hytale.component", "ComponentRegistryProxy")
private val ENTITY_STORE_TYPE =
    ClassName("com.hypixel.hytale.server.core.universe.world.storage", "EntityStore")

private val REGISTER_INTERACTION = MemberName(
    "io.github.dawidprosba.aergiadevkit.ksp.registry.hytalehelpers",
    "registerInteraction"
)
private val REGISTER_COMPONENT =
    MemberName("io.github.dawidprosba.aergiadevkit.ksp.registry.hytalehelpers", "registerComponent")
private val REGISTER_SYSTEM =
    MemberName("io.github.dawidprosba.aergiadevkit.ksp.registry.hytalehelpers", "registerSystem")

enum class RegistryType(val objectName: String, val registerFn: MemberName, val label: String) {
    INTERACTION("InteractionRegistryGenerated", REGISTER_INTERACTION, "interaction"),
    COMPONENT("ComponentRegistryGenerated", REGISTER_COMPONENT, "component"),
    SYSTEM("SystemRegistryGenerated", REGISTER_SYSTEM, "system")
}

class RegistryFileGeneratorStrategy(
    private val outputPackage: String,
    private val pluginClass: String,
    private val registryType: RegistryType,
    private val entries: List<RegistryEntryMetadata>,
    private val sourceFiles: Array<KSFile>,
    private val codeGenerator: CodeGenerator
) {
    fun generate() {
        val fileSpec = FileSpec.builder(outputPackage, registryType.objectName)
            .addFileComment("Auto-generated by RegistrationProcessor. Do not edit manually.")
            .addType(buildRegistryObject())
            .build()

        codeGenerator.createNewFile(
            dependencies = Dependencies(true, *sourceFiles),
            packageName = outputPackage,
            fileName = registryType.objectName
        ).use { stream ->
            stream.writer().use { fileSpec.writeTo(it) }
        }
    }

    private fun buildRegistryObject(): TypeSpec {
        return TypeSpec.objectBuilder(registryType.objectName)
            .addProperty(buildLoggerProperty())
            .addFunction(buildRegisterAllFunction())
            .build()
    }

    private fun buildLoggerProperty(): PropertySpec {
        val pluginClassName = ClassName.bestGuess(pluginClass)
        return PropertySpec.builder("LOGGER", HYTALE_LOGGER_TYPE)
            .initializer("%T.get(%T::class.simpleName)", HYTALE_LOGGER_TYPE, pluginClassName)
            .build()
    }

    private fun buildRegisterAllFunction(): FunSpec {
        return FunSpec.builder("registerAll")
            .addParameter("registry", buildRegistryParamType())
            .addCode(buildRegisterAllBody())
            .build()
    }

    private fun buildRegistryParamType(): TypeName {
        return when (registryType) {
            RegistryType.INTERACTION -> CODEC_MAP_REGISTRY_ASSETS_TYPE.parameterizedBy(
                INTERACTION_TYPE,
                STAR
            )

            RegistryType.COMPONENT, RegistryType.SYSTEM -> COMPONENT_REGISTRY_PROXY_TYPE.parameterizedBy(
                ENTITY_STORE_TYPE
            )
        }
    }

    private fun buildRegisterAllBody(): CodeBlock {
        return CodeBlock.builder()
            .apply {
                entries.forEach { entry ->
                    val entryClass = ClassName.bestGuess(entry.qualifiedName)
                    if (!entry.enabled) {
                        addStatement(
                            "LOGGER.atWarning().log(%S, %S)",
                            "Skipping ${registryType.label} '%s' (%s), reason -> disabled",
                            entry.qualifiedName
                        )
                    } else {
                        addStatement("%M(%T::class, registry)", registryType.registerFn, entryClass)
                    }
                }
            }
            .build()
    }
}