package io.github.dawidprosba.aergiadevkit.ksp.registry.processor.generators

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSFile
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import io.github.dawidprosba.aergiadevkit.ksp.registry.data.RegistryEntryMetadata
import io.github.dawidprosba.aergiadevkit.ksp.registry.processor.*
import io.github.dawidprosba.aergiadevkit.ksp.registry.providers.ComponentRegistrationService
import java.io.IOException

class ComponentRegistryGenerator(
    private val outputPackage: String,
    private val pluginClass: String,
    private val entries: List<RegistryEntryMetadata>,
    private val sourceFiles: Array<KSFile>,
    private val codeGenerator: CodeGenerator,
) {
    private val objectName = "ComponentRegistryGenerated"

    fun generate() {
        generateSourceFile()
        generateServiceLoaderFile()
    }

    private fun generateSourceFile() {
        val fileSpec = FileSpec.builder(outputPackage, objectName)
            .addFileComment("Auto-generated by RegistrationProcessor. Do not edit manually.")
            .addType(buildRegistryClass())
            .build()

        codeGenerator.createNewFile(
            dependencies = Dependencies(true, *sourceFiles),
            packageName = outputPackage,
            fileName = objectName,
        ).use { stream ->
            stream.writer().use { fileSpec.writeTo(it) }
        }
    }

    private fun generateServiceLoaderFile() {
        val serviceInterfaceName = ComponentRegistrationService::class.qualifiedName!!
        val serviceClassName = "$outputPackage.$objectName"

        try {
            codeGenerator.createNewFile(
                dependencies = Dependencies(true, *sourceFiles),
                packageName = "META-INF.services",
                fileName = serviceInterfaceName,
                extensionName = "",
            ).use { stream ->
                stream.write(serviceClassName.toByteArray())
            }
        } catch (e: FileAlreadyExistsException) {
            // pass
        }

    }

    private fun buildRegistryClass(): TypeSpec {
        val pluginClassName = ClassName.bestGuess(pluginClass)

        val loggerProperty = PropertySpec.builder("LOGGER", HYTALE_LOGGER_TYPE)
            .initializer("%T.get(%T::class.simpleName)", HYTALE_LOGGER_TYPE, pluginClassName)
            .build()

        val companion = TypeSpec.companionObjectBuilder()
            .addProperty(loggerProperty)
            .build()

        return TypeSpec.classBuilder(objectName)
            .addSuperinterface(COMPONENT_REGISTRATION_SERVICE_TYPE)
            .addType(companion)
            .addFunction(buildRegisterAllFunction())
            .build()
    }

    private fun buildRegisterAllFunction(): FunSpec {
        val outComponent = WildcardTypeName.producerOf(COMPONENT_CLASS.parameterizedBy(ENTITY_STORE_TYPE))
        val classOfOutComponent = ClassName("java.lang", "Class").parameterizedBy(outComponent)
        val componentTypeType = COMPONENT_TYPE_CLASS.parameterizedBy(ENTITY_STORE_TYPE, STAR)
        val returnType = ClassName("kotlin.collections", "MutableMap").parameterizedBy(classOfOutComponent, componentTypeType)

        return FunSpec.builder("registerAll")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("registry", COMPONENT_REGISTRY_PROXY_TYPE.parameterizedBy(ENTITY_STORE_TYPE))
            .returns(returnType)
            .addCode(buildRegisterAllBody(classOfOutComponent, componentTypeType))
            .build()
    }

    private fun buildRegisterAllBody(classOfOutComponent: TypeName, componentTypeType: TypeName): CodeBlock {
        return CodeBlock.builder().apply {
            addStatement("val result = mutableMapOf<%T, %T>()", classOfOutComponent, componentTypeType)
            entries.forEach { entry ->
                val entryClass = ClassName.bestGuess(entry.qualifiedName)
                if (!entry.enabled) {
                    addStatement(
                        "LOGGER.atWarning().log(%S, %S)",
                        "Skipping component '%s' (%s), reason -> disabled",
                        entry.qualifiedName,
                    )
                } else {
                    addStatement(
                        "result[%T::class.java] = %M(%T::class, registry)",
                        entryClass,
                        REGISTER_COMPONENT,
                        entryClass,
                    )
                }
            }
            addStatement("return result")
        }.build()
    }
}
