package io.github.dawidprosba.aergiadevkit.ksp.registry.processor.generators

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSFile
import com.squareup.kotlinpoet.*
import io.github.dawidprosba.aergiadevkit.ksp.registry.data.EventEntryMetadata
import io.github.dawidprosba.aergiadevkit.ksp.registry.processor.EVENT_REGISTRY_TYPE
import io.github.dawidprosba.aergiadevkit.ksp.registry.processor.HYTALE_LOGGER_TYPE
import io.github.dawidprosba.aergiadevkit.ksp.registry.processor.REGISTER_EVENT

class EventRegistryGenerator(
    private val outputPackage: String,
    private val pluginClass: String,
    private val entries: List<EventEntryMetadata>,
    private val sourceFiles: Array<KSFile>,
    private val codeGenerator: CodeGenerator,
) {
    fun generate() {
        val fileSpec = FileSpec.builder(outputPackage, OBJECT_NAME)
            .addFileComment("Auto-generated by RegistrationProcessor. Do not edit manually.")
            .addAnnotation(
                AnnotationSpec.builder(Suppress::class)
                    .addMember("%S", "UNCHECKED_CAST")
                    .build()
            )
            .addType(buildRegistryObject())
            .build()

        codeGenerator.createNewFile(
            dependencies = Dependencies(true, *sourceFiles),
            packageName = outputPackage,
            fileName = OBJECT_NAME
        ).use { stream ->
            stream.writer().use { fileSpec.writeTo(it) }
        }
    }

    private fun buildRegistryObject(): TypeSpec {
        return TypeSpec.objectBuilder(OBJECT_NAME)
            .addProperty(buildLoggerProperty())
            .addFunction(buildRegisterAllFunction())
            .build()
    }

    private fun buildLoggerProperty(): PropertySpec {
        val pluginClassName = ClassName.bestGuess(pluginClass)
        return PropertySpec.builder("LOGGER", HYTALE_LOGGER_TYPE)
            .initializer("%T.get(%T::class.simpleName)", HYTALE_LOGGER_TYPE, pluginClassName)
            .build()
    }

    private fun buildRegisterAllFunction(): FunSpec {
        return FunSpec.builder("registerAll")
            .addParameter("registry", EVENT_REGISTRY_TYPE)
            .addCode(buildRegisterAllBody())
            .build()
    }

    private fun buildRegisterAllBody(): CodeBlock {
        return CodeBlock.builder().apply {
            entries.forEach { entry ->
                val eventClass = ClassName.bestGuess(entry.eventClassQualifiedName)
                val subjectClass = ClassName.bestGuess(entry.subjectClassQualifiedName)
                val containingClass = ClassName.bestGuess(entry.containingClassQualifiedName)
                if (!entry.enabled) {
                    addStatement(
                        "LOGGER.atWarning().log(%S, %S)",
                        "Skipping event '%s' (%s), reason -> disabled",
                        entry.functionQualifiedName
                    )
                } else if (entry.hasEventParam) {
                    addStatement(
                        "%M(%T::class, %T::class.java, { event -> %T.Companion.%N(event as %L) }, registry, %S)",
                        REGISTER_EVENT, eventClass, subjectClass, containingClass, entry.functionName, entry.eventParamTypeName, entry.functionName
                    )
                } else {
                    addStatement(
                        "%M(%T::class, %T::class.java, { %T.Companion.%N() }, registry, %S)",
                        REGISTER_EVENT, eventClass, subjectClass, containingClass, entry.functionName, entry.functionName
                    )
                }
            }
        }.build()
    }

    private companion object {
        const val OBJECT_NAME = "EventRegistryGenerated"
    }
}
