package io.github.dawidprosba.aergiadevkit.ksp.registry.processor.generators

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSFile
import com.squareup.kotlinpoet.*
import io.github.dawidprosba.aergiadevkit.ksp.registry.data.RegistryEntryMetadata
import io.github.dawidprosba.aergiadevkit.ksp.registry.processor.HYTALE_LOGGER_TYPE

abstract class SimpleRegistryGenerator(
    protected val outputPackage: String,
    protected val pluginClass: String,
    protected val entries: List<RegistryEntryMetadata>,
    protected val sourceFiles: Array<KSFile>,
    protected val codeGenerator: CodeGenerator,
) {
    protected abstract val objectName: String
    protected abstract val disabledLogMessage: String
    protected abstract val registerMember: MemberName
    protected abstract val registryParameterType: TypeName

    fun generate() {
        val fileSpec = FileSpec.builder(outputPackage, objectName)
            .addFileComment("Auto-generated by RegistrationProcessor. Do not edit manually.")
            .addType(buildRegistryObject())
            .build()

        codeGenerator.createNewFile(
            dependencies = Dependencies(true, *sourceFiles),
            packageName = outputPackage,
            fileName = objectName
        ).use { stream ->
            stream.writer().use { fileSpec.writeTo(it) }
        }
    }

    private fun buildRegistryObject(): TypeSpec {
        return TypeSpec.objectBuilder(objectName)
            .addProperty(buildLoggerProperty())
            .addFunction(buildRegisterAllFunction())
            .build()
    }

    private fun buildLoggerProperty(): PropertySpec {
        val pluginClassName = ClassName.bestGuess(pluginClass)
        return PropertySpec.builder("LOGGER", HYTALE_LOGGER_TYPE)
            .initializer("%T.get(%T::class.simpleName)", HYTALE_LOGGER_TYPE, pluginClassName)
            .build()
    }

    private fun buildRegisterAllFunction(): FunSpec {
        return FunSpec.builder("registerAll")
            .addParameter("registry", registryParameterType)
            .addCode(buildRegisterAllBody())
            .build()
    }

    private fun buildRegisterAllBody(): CodeBlock {
        return CodeBlock.builder().apply {
            entries.forEach { entry ->
                val entryClass = ClassName.bestGuess(entry.qualifiedName)
                if (!entry.enabled) {
                    addStatement(
                        "LOGGER.atWarning().log(%S, %S)",
                        disabledLogMessage,
                        entry.qualifiedName
                    )
                } else {
                    addStatement("%M(%T::class, registry)", registerMember, entryClass)
                }
            }
        }.build()
    }
}
